# Установка, обновление, удаление и запуск модулей.
#
# Лаунчер ничего не знает про конкретные модули: всё, что ему нужно, лежит в
# module.json рядом с кодом модуля.

function Read-EwManifest {
    param([Parameter(Mandatory)][string]$Path)

    $m = Get-Content -LiteralPath $Path -Raw -Encoding UTF8 | ConvertFrom-Json
    foreach ($field in 'id', 'name', 'version', 'runtime', 'entry') {
        if (-not $m.$field) { throw "в манифесте нет поля «$field»" }
    }
    return $m
}

# Каталога модулей нет намеренно: сканирование папки не может разойтись с тем,
# что реально лежит в репозитории.
function Get-EwAvailable {
    param([Parameter(Mandatory)][string]$SourceDir)

    $found = @()
    $dir = Join-Path $SourceDir 'modules'
    if (-not (Test-Path -LiteralPath $dir)) { return $found }

    foreach ($d in (Get-ChildItem -LiteralPath $dir -Directory)) {
        $manifestPath = Join-Path $d.FullName 'module.json'
        if (-not (Test-Path -LiteralPath $manifestPath)) { continue }
        try {
            $m = Read-EwManifest -Path $manifestPath
        } catch {
            Write-EwWarn "Модуль «$($d.Name)» пропущен: $($_.Exception.Message)."
            continue
        }
        if ($m.runtime -ne 'python') {
            Write-EwWarn "Модуль «$($m.name)» требует рантайм «$($m.runtime)» — обновите EwScripts."
            continue
        }
        $m | Add-Member -NotePropertyName SourcePath -NotePropertyValue $d.FullName -Force
        $found += $m
    }
    return @($found | Sort-Object name)
}

function Get-EwState {
    if (Test-Path -LiteralPath $script:EwStateFile) {
        try {
            return Get-Content -LiteralPath $script:EwStateFile -Raw -Encoding UTF8 | ConvertFrom-Json
        } catch {
            Write-EwWarn 'state.json повреждён — пересобираю по установленным модулям.'
        }
    }
    return New-EwState
}

# Восстановление состояния по факту: манифесты установленных модулей — источник
# правды понадёжнее json-файла, который мог не дожить до конца записи.
function New-EwState {
    $mods = [ordered]@{}
    if (Test-Path -LiteralPath $script:EwModulesDir) {
        foreach ($d in (Get-ChildItem -LiteralPath $script:EwModulesDir -Directory)) {
            $manifestPath = Join-Path $d.FullName 'module.json'
            if (-not (Test-Path -LiteralPath $manifestPath)) { continue }
            try {
                $m = Read-EwManifest -Path $manifestPath
                $mods[$m.id] = [pscustomobject]@{ version = $m.version; installed = '' }
            } catch { }
        }
    }
    return [pscustomobject]@{
        schema  = 1
        runtime = $null
        modules = [pscustomobject]$mods
    }
}

function Save-EwState {
    param([Parameter(Mandatory)] $State)

    New-Item -ItemType Directory -Path $script:EwRoot -Force | Out-Null
    $State | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $script:EwStateFile -Encoding UTF8
}

function Get-EwInstalledVersion {
    param($State, [string]$Id)

    if ($State.modules -and ($State.modules.PSObject.Properties.Name -contains $Id)) {
        return $State.modules.$Id.version
    }
    return $null
}

function Set-EwStateModule {
    param($State, [string]$Id, [string]$Version, [string]$RuntimeVersion)

    $entry = [pscustomobject]@{
        version   = $Version
        installed = (Get-Date).ToString('o')
    }
    if ($State.modules.PSObject.Properties.Name -contains $Id) {
        $State.modules.$Id = $entry
    } else {
        $State.modules | Add-Member -NotePropertyName $Id -NotePropertyValue $entry
    }
    if ($RuntimeVersion) {
        $State.runtime = [pscustomobject]@{ kind = 'nuget-python'; version = $RuntimeVersion }
    }
}

function Remove-EwStateModule {
    param($State, [string]$Id)

    if ($State.modules.PSObject.Properties.Name -contains $Id) {
        $State.modules.PSObject.Properties.Remove($Id)
    }
}

# Пути внутри .cmd — через %LOCALAPPDATA%, а не подставленные буквально.
# cmd.exe отслеживает позицию в файле по байтовым смещениям и путается на
# многобайтовых символах, а имя пользователя вполне может быть кириллическим.
# Так файл остаётся строго в ASCII при любом имени профиля.
function New-EwLaunchCmd {
    param([Parameter(Mandatory)] $Manifest, [Parameter(Mandatory)][string]$Dest)

    $dataToken = "%EW%\data\$($Manifest.id)"
    $moduleArgs = @()
    foreach ($a in @($Manifest.args)) {
        $moduleArgs += '"' + ([string]$a).Replace('{data}', $dataToken) + '"'
    }

    $call = '"%EW%\runtime\python\python.exe" "%EW%\runtime\launch.py" ' +
            "`"%EW%\modules\$($Manifest.id)`" `"$($Manifest.entry)`""
    if ($moduleArgs.Count) { $call += ' ' + ($moduleArgs -join ' ') }
    $call += ' %*'

    $lines = @(
        '@echo off'
        'rem Generated by EwScripts. Regenerated on every install and update.'
        "title EwScripts - $($Manifest.id)"
        'set "EW=%LOCALAPPDATA%\EwScripts"'
        $call
    )
    Set-Content -LiteralPath (Join-Path $Dest 'launch.cmd') -Value $lines -Encoding Ascii
}

function New-EwShortcut {
    param([Parameter(Mandatory)] $Manifest, [Parameter(Mandatory)][string]$Dest)

    if (-not $Manifest.shortcut) { return }
    New-Item -ItemType Directory -Path $script:EwStartMenu -Force | Out-Null

    $shell = New-Object -ComObject WScript.Shell
    $lnk = $shell.CreateShortcut((Join-Path $script:EwStartMenu ($Manifest.shortcut + '.lnk')))
    $lnk.TargetPath = Join-Path $Dest 'launch.cmd'
    $lnk.WorkingDirectory = $Dest
    $lnk.Description = [string]$Manifest.summary
    $lnk.Save()
}

function Remove-EwShortcut {
    param([string]$Name)

    if (-not $Name) { return }
    $lnk = Join-Path $script:EwStartMenu ($Name + '.lnk')
    if (Test-Path -LiteralPath $lnk) { Remove-Item -LiteralPath $lnk -Force }
}

# Работающий модуль держит свою папку: cmd.exe не отпускает launch.cmd, а
# python.exe — рабочую директорию. Найти его можно по пути в командной строке,
# он уникален.
function Get-EwModuleProcess {
    param([Parameter(Mandatory)][string]$Id)

    $needle = Join-Path $script:EwModulesDir $Id
    try {
        $all = Get-CimInstance Win32_Process `
            -Filter "Name = 'python.exe' OR Name = 'pythonw.exe' OR Name = 'cmd.exe'" `
            -ErrorAction Stop
    } catch {
        return @()
    }
    return @($all | Where-Object {
        $_.CommandLine -and $_.CommandLine.IndexOf($needle, [StringComparison]::OrdinalIgnoreCase) -ge 0
    })
}

function Stop-EwModuleProcess {
    param([Parameter(Mandatory)][string]$Id)

    foreach ($p in (Get-EwModuleProcess -Id $Id)) {
        Stop-Process -Id $p.ProcessId -Force -ErrorAction SilentlyContinue
    }
    # Папку Windows отпускает не в тот же миг, когда процесс умирает.
    for ($i = 0; $i -lt 25; $i++) {
        if (-not @(Get-EwModuleProcess -Id $Id).Count) { return $true }
        Start-Sleep -Milliseconds 200
    }
    return $false
}

function Confirm-EwModuleStopped {
    param(
        [Parameter(Mandatory)][string]$Id,
        [Parameter(Mandatory)][string]$Name,
        [string]$Action = 'Обновление'
    )

    if (-not @(Get-EwModuleProcess -Id $Id).Count) { return $true }

    Write-EwWarn "«$Name» сейчас запущен. $Action заменит его файлы."
    if (-not (Read-EwConfirm 'Закрыть его и продолжить?')) {
        Write-EwInfo 'Отменено, ничего не изменилось.'
        return $false
    }
    if (-not (Stop-EwModuleProcess -Id $Id)) {
        Write-EwErr 'Не удалось закрыть. Закройте окно модуля вручную и повторите.'
        return $false
    }
    Write-EwStep 'Запущенный модуль закрыт.'
    return $true
}

# Копируется только код модуля. Всё, что модуль наживает при работе — логи,
# данные, libs, кэш Python, — в установку попадать не должно: иначе машина
# разработчика протащит свой мусор в чужую установку, а libs приедет устаревшим.
function Copy-EwModuleFiles {
    param([Parameter(Mandatory)][string]$Source, [Parameter(Mandatory)][string]$Destination)

    $skipDirs = @('logs', 'data', 'libs', '__pycache__', '.venv', '.git')
    $skipFiles = @('*.pyc', '*.pyo')

    New-Item -ItemType Directory -Path $Destination -Force | Out-Null
    $prefix = $Source.TrimEnd('\').Length + 1

    foreach ($item in (Get-ChildItem -LiteralPath $Source -Recurse -Force)) {
        $relative = $item.FullName.Substring($prefix)
        $segments = @($relative -split '\\')

        if ($item.PSIsContainer) { $dirSegments = $segments }
        elseif ($segments.Count -gt 1) { $dirSegments = $segments[0..($segments.Count - 2)] }
        else { $dirSegments = @() }

        $skip = $false
        foreach ($segment in $dirSegments) {
            if ($skipDirs -contains $segment) { $skip = $true; break }
        }
        if ($skip) { continue }

        $target = Join-Path $Destination $relative
        if ($item.PSIsContainer) {
            New-Item -ItemType Directory -Path $target -Force | Out-Null
            continue
        }

        foreach ($pattern in $skipFiles) {
            if ($item.Name -like $pattern) { $skip = $true; break }
        }
        if ($skip) { continue }

        New-Item -ItemType Directory -Path (Split-Path $target -Parent) -Force | Out-Null
        Copy-Item -LiteralPath $item.FullName -Destination $target -Force
    }
}

# Модуль может иметь побочные эффекты за пределами своей папки — например,
# записаться в контекстное меню. Лаунчер про них ничего не знает: он лишь зовёт
# точку входа модуля с оговорёнными в манифесте аргументами.
function Invoke-EwModuleHook {
    param(
        [Parameter(Mandatory)] $Manifest,
        [Parameter(Mandatory)][string]$Dest,
        $HookArgs,
        [string]$Title = 'Настраиваю модуль.'
    )

    $data = Join-Path $script:EwDataDir $Manifest.id
    $prepared = @(@($HookArgs) | Where-Object { $_ } | ForEach-Object {
        ([string]$_).Replace('{data}', $data)
    })
    if (-not $prepared.Count) { return }

    Write-EwStep $Title
    New-Item -ItemType Directory -Path $data -Force | Out-Null
    & $script:EwPyExe (Join-Path $script:EwRuntimeDir 'launch.py') $Dest $Manifest.entry $prepared
    if ($LASTEXITCODE -ne 0) {
        throw "модуль не смог выполнить $($prepared -join ' ')"
    }
}

function Install-EwModule {
    param(
        [Parameter(Mandatory)] $Manifest,
        [Parameter(Mandatory)] $RuntimeSpec,
        [Parameter(Mandatory)] $State
    )

    Install-EwRuntime -Spec $RuntimeSpec
    Install-EwLaunchShim -SourceDir $script:EwSource

    $dest = Join-Path $script:EwModulesDir $Manifest.id
    $stage = "$dest.new"

    Write-EwStep 'Копирую файлы модуля.'
    New-Item -ItemType Directory -Path $script:EwModulesDir -Force | Out-Null
    if (Test-Path -LiteralPath $stage) { Remove-Item -LiteralPath $stage -Recurse -Force }
    Copy-EwModuleFiles -Source $Manifest.SourcePath -Destination $stage

    try {
        $requires = @($Manifest.requires | Where-Object { $_ })
        if ($requires.Count) {
            Write-EwStep "Ставлю зависимости: $($requires -join ', ')."
            & $script:EwPyExe -m pip install --quiet --disable-pip-version-check `
                --no-warn-script-location --target (Join-Path $stage 'libs') $requires
            if ($LASTEXITCODE -ne 0) { throw 'pip не смог поставить зависимости' }
        }
    } catch {
        Remove-Item -LiteralPath $stage -Recurse -Force -ErrorAction SilentlyContinue
        throw
    }

    # Подмена целиком: код заменяется, папка data остаётся нетронутой.
    #
    # Старую версию сначала отодвигаем, а не удаляем. Remove-Item -Recurse сносит
    # сначала содержимое и только потом саму папку: на занятой папке он успевал
    # стереть код и падал уже на ней, оставляя модуль выпотрошенным — и его
    # приходилось ставить заново. Переименование либо проходит целиком, либо не
    # делает ничего, поэтому рабочая установка не может пострадать.
    $backup = "$dest.old"
    if (Test-Path -LiteralPath $backup) {
        Remove-Item -LiteralPath $backup -Recurse -Force -ErrorAction SilentlyContinue
    }

    $hadPrevious = Test-Path -LiteralPath $dest
    if ($hadPrevious) {
        try {
            Move-Item -LiteralPath $dest -Destination $backup -ErrorAction Stop
        } catch {
            Remove-Item -LiteralPath $stage -Recurse -Force -ErrorAction SilentlyContinue
            throw "файлы модуля заняты — закройте запущенный «$($Manifest.name)» и повторите"
        }
    }

    try {
        Move-Item -LiteralPath $stage -Destination $dest -ErrorAction Stop
    } catch {
        if ($hadPrevious) { Move-Item -LiteralPath $backup -Destination $dest -Force }
        throw
    }

    New-Item -ItemType Directory -Path (Join-Path $script:EwDataDir $Manifest.id) -Force | Out-Null

    New-EwLaunchCmd -Manifest $Manifest -Dest $dest
    New-EwShortcut -Manifest $Manifest -Dest $dest

    # Хук выполняется до того, как выброшена резервная копия. Если модуль не смог
    # себя настроить, возвращаем прежнюю версию целиком: половинчатая установка
    # хуже отказа, потому что выглядит рабочей.
    if ($Manifest.postInstall) {
        try {
            Invoke-EwModuleHook -Manifest $Manifest -Dest $dest -HookArgs $Manifest.postInstall
        } catch {
            Remove-Item -LiteralPath $dest -Recurse -Force -ErrorAction SilentlyContinue
            if ($hadPrevious) { Move-Item -LiteralPath $backup -Destination $dest -Force }
            throw
        }
    }

    if ($hadPrevious) {
        Remove-Item -LiteralPath $backup -Recurse -Force -ErrorAction SilentlyContinue
    }

    Set-EwStateModule -State $State -Id $Manifest.id -Version $Manifest.version `
                      -RuntimeVersion $RuntimeSpec.version
    Save-EwState $State
}

function Remove-EwModule {
    param([Parameter(Mandatory)][string]$Id, [Parameter(Mandatory)] $State, [switch]$WithData)

    $dest = Join-Path $script:EwModulesDir $Id

    $shortcut = $null
    $installed = $null
    $manifestPath = Join-Path $dest 'module.json'
    if (Test-Path -LiteralPath $manifestPath) {
        try {
            $installed = Read-EwManifest -Path $manifestPath
            $shortcut = $installed.shortcut
        } catch { }
    }

    # Модуль убирает за собой сам, пока его файлы ещё на месте. Ошибка здесь не
    # должна мешать удалению: иначе сломанный модуль стало бы невозможно снести.
    if ($installed -and $installed.preUninstall) {
        try {
            Invoke-EwModuleHook -Manifest $installed -Dest $dest `
                                -HookArgs $installed.preUninstall -Title 'Убираю следы модуля.'
        } catch {
            Write-EwWarn "Модуль не смог убрать за собой: $($_.Exception.Message)"
        }
    }

    # Папку сначала отодвигаем — по той же причине, что и при обновлении: на
    # занятой папке Remove-Item -Recurse стирает содержимое и падает. И только
    # когда это удалось, трогаем ярлык и состояние: иначе неудачное удаление
    # оставило бы модуль без ярлыка, но с файлами.
    if (Test-Path -LiteralPath $dest) {
        $trash = "$dest.old"
        if (Test-Path -LiteralPath $trash) {
            Remove-Item -LiteralPath $trash -Recurse -Force -ErrorAction SilentlyContinue
        }
        try {
            Move-Item -LiteralPath $dest -Destination $trash -ErrorAction Stop
        } catch {
            throw "файлы модуля заняты — закройте запущенный модуль и повторите"
        }
        Remove-Item -LiteralPath $trash -Recurse -Force -ErrorAction SilentlyContinue
    }

    Remove-EwShortcut -Name $shortcut

    if ($WithData) {
        $data = Join-Path $script:EwDataDir $Id
        if (Test-Path -LiteralPath $data) { Remove-Item -LiteralPath $data -Recurse -Force }
    }

    Remove-EwStateModule -State $State -Id $Id
    Save-EwState $State
}

function Start-EwModule {
    param([Parameter(Mandatory)][string]$Id)

    $dir = Join-Path $script:EwModulesDir $Id
    $cmd = Join-Path $dir 'launch.cmd'
    if (-not (Test-Path -LiteralPath $cmd)) { throw "модуль «$Id» не установлен" }
    # Рабочая директория та же, что ставит ярлык: запуск из меню и из Пуска
    # должны вести себя одинаково, иначе модуль ведёт себя по-разному в
    # зависимости от того, как его открыли.
    Start-Process -FilePath $cmd -WorkingDirectory $dir
}
