# Установка, обновление, удаление и запуск модулей.
#
# Лаунчер ничего не знает про конкретные модули: всё, что ему нужно, лежит в
# module.json рядом с кодом модуля.

function Read-EwManifest {
    param([Parameter(Mandatory)][string]$Path)

    $m = Get-Content -LiteralPath $Path -Raw -Encoding UTF8 | ConvertFrom-Json
    foreach ($field in 'id', 'name', 'version', 'runtime', 'entry') {
        if (-not $m.$field) { throw "в манифесте нет поля «$field»" }
    }
    return $m
}

# Каталога модулей нет намеренно: сканирование папки не может разойтись с тем,
# что реально лежит в репозитории.
function Get-EwAvailable {
    param([Parameter(Mandatory)][string]$SourceDir)

    $found = @()
    $dir = Join-Path $SourceDir 'modules'
    if (-not (Test-Path -LiteralPath $dir)) { return $found }

    foreach ($d in (Get-ChildItem -LiteralPath $dir -Directory)) {
        $manifestPath = Join-Path $d.FullName 'module.json'
        if (-not (Test-Path -LiteralPath $manifestPath)) { continue }
        try {
            $m = Read-EwManifest -Path $manifestPath
        } catch {
            Write-EwWarn "Модуль «$($d.Name)» пропущен: $($_.Exception.Message)."
            continue
        }
        if ($m.runtime -ne 'python') {
            Write-EwWarn "Модуль «$($m.name)» требует рантайм «$($m.runtime)» — обновите EwScripts."
            continue
        }
        $m | Add-Member -NotePropertyName SourcePath -NotePropertyValue $d.FullName -Force
        $found += $m
    }
    return @($found | Sort-Object name)
}

function Get-EwState {
    if (Test-Path -LiteralPath $script:EwStateFile) {
        try {
            return Get-Content -LiteralPath $script:EwStateFile -Raw -Encoding UTF8 | ConvertFrom-Json
        } catch {
            Write-EwWarn 'state.json повреждён — пересобираю по установленным модулям.'
        }
    }
    return New-EwState
}

# Восстановление состояния по факту: манифесты установленных модулей — источник
# правды понадёжнее json-файла, который мог не дожить до конца записи.
function New-EwState {
    $mods = [ordered]@{}
    if (Test-Path -LiteralPath $script:EwModulesDir) {
        foreach ($d in (Get-ChildItem -LiteralPath $script:EwModulesDir -Directory)) {
            $manifestPath = Join-Path $d.FullName 'module.json'
            if (-not (Test-Path -LiteralPath $manifestPath)) { continue }
            try {
                $m = Read-EwManifest -Path $manifestPath
                $mods[$m.id] = [pscustomobject]@{ version = $m.version; installed = '' }
            } catch { }
        }
    }
    return [pscustomobject]@{
        schema  = 1
        runtime = $null
        modules = [pscustomobject]$mods
    }
}

function Save-EwState {
    param([Parameter(Mandatory)] $State)

    New-Item -ItemType Directory -Path $script:EwRoot -Force | Out-Null
    $State | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $script:EwStateFile -Encoding UTF8
}

function Get-EwInstalledVersion {
    param($State, [string]$Id)

    if ($State.modules -and ($State.modules.PSObject.Properties.Name -contains $Id)) {
        return $State.modules.$Id.version
    }
    return $null
}

function Set-EwStateModule {
    param($State, [string]$Id, [string]$Version, [string]$RuntimeVersion)

    $entry = [pscustomobject]@{
        version   = $Version
        installed = (Get-Date).ToString('o')
    }
    if ($State.modules.PSObject.Properties.Name -contains $Id) {
        $State.modules.$Id = $entry
    } else {
        $State.modules | Add-Member -NotePropertyName $Id -NotePropertyValue $entry
    }
    if ($RuntimeVersion) {
        $State.runtime = [pscustomobject]@{ kind = 'nuget-python'; version = $RuntimeVersion }
    }
}

function Remove-EwStateModule {
    param($State, [string]$Id)

    if ($State.modules.PSObject.Properties.Name -contains $Id) {
        $State.modules.PSObject.Properties.Remove($Id)
    }
}

# Пути внутри .cmd — через %LOCALAPPDATA%, а не подставленные буквально.
# cmd.exe отслеживает позицию в файле по байтовым смещениям и путается на
# многобайтовых символах, а имя пользователя вполне может быть кириллическим.
# Так файл остаётся строго в ASCII при любом имени профиля.
function New-EwLaunchCmd {
    param([Parameter(Mandatory)] $Manifest, [Parameter(Mandatory)][string]$Dest)

    $dataToken = "%EW%\data\$($Manifest.id)"
    $moduleArgs = @()
    foreach ($a in @($Manifest.args)) {
        $moduleArgs += '"' + ([string]$a).Replace('{data}', $dataToken) + '"'
    }

    $call = '"%EW%\runtime\python\python.exe" "%EW%\runtime\launch.py" ' +
            "`"%EW%\modules\$($Manifest.id)`" `"$($Manifest.entry)`""
    if ($moduleArgs.Count) { $call += ' ' + ($moduleArgs -join ' ') }
    $call += ' %*'

    $lines = @(
        '@echo off'
        'rem Generated by EwScripts. Regenerated on every install and update.'
        "title EwScripts - $($Manifest.id)"
        'set "EW=%LOCALAPPDATA%\EwScripts"'
        $call
    )
    Set-Content -LiteralPath (Join-Path $Dest 'launch.cmd') -Value $lines -Encoding Ascii
}

function New-EwShortcut {
    param([Parameter(Mandatory)] $Manifest, [Parameter(Mandatory)][string]$Dest)

    if (-not $Manifest.shortcut) { return }
    New-Item -ItemType Directory -Path $script:EwStartMenu -Force | Out-Null

    $shell = New-Object -ComObject WScript.Shell
    $lnk = $shell.CreateShortcut((Join-Path $script:EwStartMenu ($Manifest.shortcut + '.lnk')))
    $lnk.TargetPath = Join-Path $Dest 'launch.cmd'
    $lnk.WorkingDirectory = $Dest
    $lnk.Description = [string]$Manifest.summary
    $lnk.Save()
}

function Remove-EwShortcut {
    param([string]$Name)

    if (-not $Name) { return }
    $lnk = Join-Path $script:EwStartMenu ($Name + '.lnk')
    if (Test-Path -LiteralPath $lnk) { Remove-Item -LiteralPath $lnk -Force }
}

# Копируется только код модуля. Всё, что модуль наживает при работе — логи,
# данные, libs, кэш Python, — в установку попадать не должно: иначе машина
# разработчика протащит свой мусор в чужую установку, а libs приедет устаревшим.
function Copy-EwModuleFiles {
    param([Parameter(Mandatory)][string]$Source, [Parameter(Mandatory)][string]$Destination)

    $skipDirs = @('logs', 'data', 'libs', '__pycache__', '.venv', '.git')
    $skipFiles = @('*.pyc', '*.pyo')

    New-Item -ItemType Directory -Path $Destination -Force | Out-Null
    $prefix = $Source.TrimEnd('\').Length + 1

    foreach ($item in (Get-ChildItem -LiteralPath $Source -Recurse -Force)) {
        $relative = $item.FullName.Substring($prefix)
        $segments = @($relative -split '\\')

        if ($item.PSIsContainer) { $dirSegments = $segments }
        elseif ($segments.Count -gt 1) { $dirSegments = $segments[0..($segments.Count - 2)] }
        else { $dirSegments = @() }

        $skip = $false
        foreach ($segment in $dirSegments) {
            if ($skipDirs -contains $segment) { $skip = $true; break }
        }
        if ($skip) { continue }

        $target = Join-Path $Destination $relative
        if ($item.PSIsContainer) {
            New-Item -ItemType Directory -Path $target -Force | Out-Null
            continue
        }

        foreach ($pattern in $skipFiles) {
            if ($item.Name -like $pattern) { $skip = $true; break }
        }
        if ($skip) { continue }

        New-Item -ItemType Directory -Path (Split-Path $target -Parent) -Force | Out-Null
        Copy-Item -LiteralPath $item.FullName -Destination $target -Force
    }
}

function Install-EwModule {
    param(
        [Parameter(Mandatory)] $Manifest,
        [Parameter(Mandatory)] $RuntimeSpec,
        [Parameter(Mandatory)] $State
    )

    Install-EwRuntime -Spec $RuntimeSpec
    Install-EwLaunchShim -SourceDir $script:EwSource

    $dest = Join-Path $script:EwModulesDir $Manifest.id
    $stage = "$dest.new"

    Write-EwStep 'Копирую файлы модуля.'
    New-Item -ItemType Directory -Path $script:EwModulesDir -Force | Out-Null
    if (Test-Path -LiteralPath $stage) { Remove-Item -LiteralPath $stage -Recurse -Force }
    Copy-EwModuleFiles -Source $Manifest.SourcePath -Destination $stage

    try {
        $requires = @($Manifest.requires | Where-Object { $_ })
        if ($requires.Count) {
            Write-EwStep "Ставлю зависимости: $($requires -join ', ')."
            & $script:EwPyExe -m pip install --quiet --disable-pip-version-check `
                --no-warn-script-location --target (Join-Path $stage 'libs') $requires
            if ($LASTEXITCODE -ne 0) { throw 'pip не смог поставить зависимости' }
        }
    } catch {
        Remove-Item -LiteralPath $stage -Recurse -Force -ErrorAction SilentlyContinue
        throw
    }

    # Подмена целиком: код заменяется, папка data остаётся нетронутой.
    if (Test-Path -LiteralPath $dest) { Remove-Item -LiteralPath $dest -Recurse -Force }
    Move-Item -LiteralPath $stage -Destination $dest

    New-Item -ItemType Directory -Path (Join-Path $script:EwDataDir $Manifest.id) -Force | Out-Null

    New-EwLaunchCmd -Manifest $Manifest -Dest $dest
    New-EwShortcut -Manifest $Manifest -Dest $dest

    Set-EwStateModule -State $State -Id $Manifest.id -Version $Manifest.version `
                      -RuntimeVersion $RuntimeSpec.version
    Save-EwState $State
}

function Remove-EwModule {
    param([Parameter(Mandatory)][string]$Id, [Parameter(Mandatory)] $State, [switch]$WithData)

    $dest = Join-Path $script:EwModulesDir $Id

    $shortcut = $null
    $manifestPath = Join-Path $dest 'module.json'
    if (Test-Path -LiteralPath $manifestPath) {
        try { $shortcut = (Read-EwManifest -Path $manifestPath).shortcut } catch { }
    }
    Remove-EwShortcut -Name $shortcut

    if (Test-Path -LiteralPath $dest) { Remove-Item -LiteralPath $dest -Recurse -Force }

    if ($WithData) {
        $data = Join-Path $script:EwDataDir $Id
        if (Test-Path -LiteralPath $data) { Remove-Item -LiteralPath $data -Recurse -Force }
    }

    Remove-EwStateModule -State $State -Id $Id
    Save-EwState $State
}

function Start-EwModule {
    param([Parameter(Mandatory)][string]$Id)

    $cmd = Join-Path (Join-Path $script:EwModulesDir $Id) 'launch.cmd'
    if (-not (Test-Path -LiteralPath $cmd)) { throw "модуль «$Id» не установлен" }
    Start-Process -FilePath $cmd
}
